# Generated by Django 4.2.7 on 2023-12-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_article_image_news_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.URLField(null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
