# Generated by Django 4.2.7 on 2023-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_options_alter_article_anouncement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default=0, max_length=150, verbose_name='Источник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('АН', 'Астрономия'), ('К', 'Космонавтика'), ('АФ', 'Астрофизика')], max_length=20, verbose_name='Категории'),
        ),
    ]
