# Generated by Django 4.2.7 on 2023-11-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_source_alter_article_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(default=0, max_length=150, verbose_name='Название источника'),
            preserve_default=False,
        ),
    ]
