# Generated by Django 4.2.7 on 2023-11-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_source_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='source_name',
            new_name='sourcename',
        ),
    ]
