# Generated by Django 4.2.7 on 2023-12-18 18:28

from django.db import migrations, models
import django.db.models.deletion
import news.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_viewcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcount',
            options={'ordering': ('-view_date',), 'verbose_name': 'Счетчик просмотров', 'verbose_name_plural': 'Счетчики просмотров'},
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, validators=[news.validators.russian_email], verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='news.article', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='ip-адрес'),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='view_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра'),
        ),
    ]
