# Generated by Django 4.2.7 on 2023-12-18 20:43

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('nickname', models.CharField(max_length=100, verbose_name='Имя автора (псевдоним)')),
                ('birthdate', models.DateField(null=True, verbose_name='День рождения')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('N/A', 'Не определен')], max_length=20, null=True, verbose_name='Пол')),
                ('account_image', models.ImageField(default='default.jpg', upload_to='account_images', verbose_name='Фото аккаунта')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ['user', 'gender'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Исправлено')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, validators=[users.validators.russian_email], verbose_name='Адрес электронной почты')),
                ('message', ckeditor.fields.RichTextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.article', verbose_name='Новость')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['create_at', 'article', 'user'],
            },
        ),
    ]
