# Generated by Django 4.2.7 on 2023-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_options_alter_account_account_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=100, verbose_name='Имя автора (псевдоним)'),
        ),
    ]
