# Generated by Django 4.2.7 on 2023-12-18 18:28

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_viewcount_options_alter_article_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_favoritearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, validators=[users.validators.russian_email], verbose_name='Адрес электронной почты')),
                ('message', ckeditor.fields.RichTextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='favoritearticle',
            options={'ordering': ['create_at', 'article', 'user'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.article', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
