# Generated by Django 4.2.7 on 2023-12-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contactform_alter_favoritearticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
